services:
  docs:
    image: quick_serve_local_docs
    container_name: quick_serve_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./quick_serve:/app/quick_serve:z
    ports:
      - '9000:9000'
    command: /start-docs
