services:
  web:
    image: python:3.12
    container_name: django-app
    command: >
      sh -c "pip install -r requirements/local.txt &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - USE_DOCKER=yes
      - IPYTHONDIR=/app/.ipython
      - DJANGO_SECRET_KEY=8joWi5JinHUi3vT20XYwnjomsYGLrtHc2VFqfs1dS447QjJWK4t5UZEdFj95u7Y6
      - DJANGO_ALLOWED_HOSTS=localhost
      - DATABASE_URL=postgres://postgres:2x+2y=26@db:5432/quick_serve
      - POSTGRES_DB=quick_serve
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=2x+2y=26
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: postgres-db
    ports:
      - "5432:5432" # Expose PostgreSQL port
    environment:
      - POSTGRES_DB=quick_serve
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=2x+2y=26
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
